### start session
POST http://localhost:9000/session/start

{
  "chargePointId": "CP_1",
  "chargeCardId": "CC_1"
}


### stop session
POST http://localhost:9000/session/stop

{
  "sessionId": "fb01da98-6fc4-469d-b1fb-bc0ca4f37c25"
}

### 950 x 390
