version: '3.7'

services:

############# APPLICATION STACK - BEGIN #############

  db_charging_service:
    image: postgres:13
    ports:
      - "5411:5432"
    environment:
      - POSTGRES_PASSWORD=db_charging_service
      - POSTGRES_USER=db_charging_service

  db_billing_service:
    image: postgres:13
    ports:
      - "5412:5432"
    environment:
      - POSTGRES_PASSWORD=db_billing_service
      - POSTGRES_USER=db_billing_service

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
